services:
  calc17:
    build:
      context: ms_prueba_17
      args:
        JAVA_VERSION: 17
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  calc21:
    build:
      context: ms_prueba_21
      args:
        JAVA_VERSION: 21
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  calc25:
    build:
      context: ms_prueba_25
      args:
        JAVA_VERSION: 25
    environment:
      - PORT=8083
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
