{
 "title": "Java Machine Comparation",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (max(process_start_time_seconds{job=\"calc17\"}))",
     "legendFormat": "Calc17"
    },
    {
     "expr": "time() - (max(process_start_time_seconds{job=\"calc21\"}))",
     "legendFormat": "Calc21"
    },
    {
     "expr": "time() - (max(process_start_time_seconds{job=\"calc25\"}))",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  sum(jvm_memory_used_bytes{job=~\"calc17\"}) by (job) \n  / \n  sum(jvm_memory_max_bytes{job=~\"calc17\"}) by (job)\n)",
     "legendFormat": "Calc17"
    },
    {
     "expr": "1 - (\n  sum(jvm_memory_used_bytes{job=~\"calc21\"}) by (job) \n  / \n  sum(jvm_memory_max_bytes{job=~\"calc21\"}) by (job)\n)",
     "legendFormat": "Calc21"
    },
    {
     "expr": "1 - (\n  sum(jvm_memory_used_bytes{job=~\"calc25\"}) by (job) \n  / \n  sum(jvm_memory_max_bytes{job=~\"calc25\"}) by (job)\n)",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"calc17\"}) / sum(jvm_memory_max_bytes{job=~\"calc17\"})",
     "legendFormat": "Calc17"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"calc21\"}) / sum(jvm_memory_max_bytes{job=~\"calc21\"})",
     "legendFormat": "Calc21"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"calc25\"}) / sum(jvm_memory_max_bytes{job=~\"calc25\"})",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "TPS Promedio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"calc17\", uri!~\"/actuator.*\"}[$__range])) by (job)",
     "legendFormat": "Calc17"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"calc21\", uri!~\"/actuator.*\"}[$__range])) by (job)",
     "legendFormat": "Calc21"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"calc25\", uri!~\"/actuator.*\"}[$__range])) by (job)",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "Tiempo Promedio Respuesta",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_server_requests_seconds_sum{job=~\"calc17\", uri!~\"/actuator.*\"}[$__range]))\n  /\n  sum(rate(http_server_requests_seconds_count{job=~\"calc17\", uri!~\"/actuator.*\"}[$__range]))\n)",
     "legendFormat": "Calc17"
    },
    {
     "expr": "(\n  sum(rate(http_server_requests_seconds_sum{job=~\"calc21\", uri!~\"/actuator.*\"}[$__range]))\n  /\n  sum(rate(http_server_requests_seconds_count{job=~\"calc21\", uri!~\"/actuator.*\"}[$__range]))\n)\n",
     "legendFormat": "Calc21"
    },
    {
     "expr": "(\n  sum(rate(http_server_requests_seconds_sum{job=~\"calc25\", uri!~\"/actuator.*\"}[$__range]))\n  /\n  sum(rate(http_server_requests_seconds_count{job=~\"calc25\", uri!~\"/actuator.*\"}[$__range]))\n)\n",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_files_open_files{job=\"calc17\"}[$__range])",
     "legendFormat": "Calc17"
    },
    {
     "expr": "max_over_time(process_files_open_files{job=\"calc21\"}[$__range])",
     "legendFormat": "Calc21"
    },
    {
     "expr": "max_over_time(process_files_open_files{job=\"calc25\"}[$__range])",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "Max. File Descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_max_files{job=\"calc17\"}",
     "legendFormat": "Calc17"
    },
    {
     "expr": "process_files_max_files{job=\"calc21\"}",
     "legendFormat": "Calc21"
    },
    {
     "expr": "process_files_max_files{job=\"calc25\"}",
     "legendFormat": "Calc25"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=~\"calc17|calc21|calc25\"}",
     "legendFormat": "Cpu Process - {{job}}"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"calc17\"})",
     "legendFormat": "JVM Process - calc17"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"calc21\"})",
     "legendFormat": "JVM Process - calc21"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"calc25\"})",
     "legendFormat": "JVM Process - calc25"
    }
   ]
  },
  {
   "title": "Heap Memory (Eden)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (jvm_memory_used_bytes{area=\"heap\", job=~\"calc17|calc21|calc25\"})",
     "legendFormat": "Used - calc25"
    }
   ]
  },
  {
   "title": "NonHeap Memory (Metaspace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (jvm_memory_used_bytes{area=\"nonheap\", job=~\"calc17|calc21|calc25\"})",
     "legendFormat": "Used - calc17"
    }
   ]
  },
  {
   "title": "Latency Comparison",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{job=\"calc17\", uri!~\"/actuator.*\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"calc17\", uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "Used - calc17"
    },
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{job=\"calc21\", uri!~\"/actuator.*\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"calc21\", uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "Used - calc21"
    },
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{job=\"calc25\", uri!~\"/actuator.*\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"calc25\", uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "Used - calc25"
    }
   ]
  },
  { "title": "Garbach Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=~\".*Eden Space\",job=~\"calc17|calc21|calc25\"}",
     "legendFormat": "Used - {{job}}"
    }
   ]
  },
  {
   "title": "Tenured Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=~\"Tenured Gen\",job=~\"calc17|calc21|calc25\"}",
     "legendFormat": "Used - {{job}}"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=~\".*Survivor Space\",job=~\"calc17|calc21|calc25\"}",
     "legendFormat": "Used - {{job}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Metaspace\",job=~\"calc17|calc21|calc25\"}",
     "legendFormat": "Used - {{job}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Compressed Class Space\",job=~\"calc17|calc21|calc25\"}",
     "legendFormat": "Used - {{job}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{id=~\".*CodeHeap.*\",job=~\"calc17\"})",
     "legendFormat": "Used - calc17"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{id=~\".*CodeHeap.*\",job=~\"calc21\"})",
     "legendFormat": "{{pool}} Used - calc21"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{id=~\".*CodeHeap.*\",job=~\"calc25\"})",
     "legendFormat": "Used - calc25"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(jvm_memory_used_bytes{area=\"heap\", id=\"Eden Space\", job=~\"calc17\"}[$__range])",
     "legendFormat": "Used - calc17 "
    },
    {
     "expr": "max_over_time(jvm_memory_used_bytes{area=\"heap\", id=\"Eden Space\", job=~\"calc21\"}[$__range])",
     "legendFormat": "Used - calc21"
    },
    {
     "expr": "max_over_time(jvm_memory_used_bytes{area=\"heap\", id=\"Eden Space\", job=~\"calc25\"}[$__range])",
     "legendFormat": "Used - calc25"
    }
   ]
  },
  {
   "title": "NonHeap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(jvm_memory_used_bytes{area=\"nonheap\", id=\"Metaspace\", job=~\"calc17\"}[$__range])",
     "legendFormat": "Used - calc17"
    },
    {
     "expr": "max_over_time(jvm_memory_used_bytes{area=\"nonheap\", id=\"Metaspace\", job=~\"calc21\"}[$__range])",
     "legendFormat": "Used - calc21"
    },
    {
     "expr": "max_over_time(jvm_memory_used_bytes{area=\"nonheap\", id=\"Metaspace\",job=~\"calc25\"}[$__range])",
     "legendFormat": "Used - calc25"
    }
   ]
  },
  {
   "title": "Garbage Collection Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{job=\"calc17\"}[$__interval]))",
     "legendFormat": "Calc17"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{job=\"calc21\"}[$__interval]))",
     "legendFormat": "Calc21"
    },
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{job=\"calc25\"}[$__interval]))",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{job=\"calc17\"}[$__interval]))",
     "legendFormat": "Calc17"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{job=\"calc21\"}[$__interval]))",
     "legendFormat": "Calc21"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{job=\"calc25\"}[$__interval]))",
     "legendFormat": "Calc25"
    }
   ]
  },
  {
   "title": "GC Throughput",
   "type": "stat",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_pause_seconds_sum{job=\"calc17\"}))-\n        sum(min(jvm_gc_pause_seconds_sum{job=\"calc17\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput Calc17"
    },
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_pause_seconds_sum{job=\"calc21\"}))-\n        sum(min(jvm_gc_pause_seconds_sum{job=\"calc21\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput Calc21"
    },
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_pause_seconds_sum{job=\"calc25\"}))-\n        sum(min(jvm_gc_pause_seconds_sum{job=\"calc25\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput Calc25"
    }
   ]
  },
  {
   "title": "GC Throughput Evolution",
   "type": "timeseries",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.  The way it is built does not work for multiple simultaneous JVMs, so accuracy requires selecting only one.",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_pause_seconds_sum{job=\"calc17\"}))-\n        sum(min(jvm_gc_pause_seconds_sum{job=\"calc17\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput Calc17"
    },
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_pause_seconds_sum{job=\"calc21\"}))-\n        sum(min(jvm_gc_pause_seconds_sum{job=\"calc21\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput Calc21"
    },
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_pause_seconds_sum{job=\"calc25\"}))-\n        sum(min(jvm_gc_pause_seconds_sum{job=\"calc25\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput Calc25"
    }
   ]
  },
  {
   "title": "GC Time (period)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{job=\"calc17\"}[$__range]))",
     "legendFormat": "Calc17"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{job=\"calc21\"}[$__range]))",
     "legendFormat": "Calc21"
    },
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_sum{job=\"calc25\"}[$__range]))",
     "legendFormat": "Calc25"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Current Threads Calc17",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"calc17\"}",
     "legendFormat": "{{job}}-{{state}}"
    }
   ]
  },
  {
   "title": "Current Threads Calc21",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"calc21\"}",
     "legendFormat": "{{job}}-{{state}}"
    }
   ]
  },
  {
   "title": "Current Threads Calc25",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"calc25\"}",
     "legendFormat": "{{job}}-{{state}}"
    }
   ]
  },
  {
   "title": "Thread State Calc17",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"calc17\"}",
     "legendFormat": "{{state}} - {{job}}"
    }
   ]
  },
  {
   "title": "Thread State Calc25",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 93 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"calc25\"}",
     "legendFormat": "{{state}} - {{job}}"
    }
   ]
  },
  {
   "title": "Thread State Calc21",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 93 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"calc21\"}",
     "legendFormat": "{{state}} - {{job}}"
    }
   ]
  }
 ]
}